onlyBuiltDependencies:
  - esbuild

overrides:
  ajv@<6.14.0: ">=6.14.0 <7"
  devalue@<=5.6.2: ">=5.6.3"
  diff@>=6.0.0 <8.0.3: ">=8.0.3"
  minimatch@<10.2.1: ">=10.2.1"
  tar@<7.5.7: ">=7.5.7"
  tar@<7.5.8: ">=7.5.8"
  tar@<=7.5.2: ">=7.5.3"
  tar@<=7.5.3: ">=7.5.4"
